import type {Metadata} from 'next';
import './globals.css';
import { LanguageProvider } from '@/context/language-context';
import { FirebaseProvider } from '@/firebase/provider';

export const metadata: Metadata = {
  title: 'ARIB',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-body antialiased">
        <FirebaseProvider>
          <LanguageProvider>
            {children}
          </LanguageProvider>
        </FirebaseProvider>
      </body>
    </html>
  );
}
